### ISSUE TITLE
Pydantic 2.9 break the package

### ISSUE THREAD

**Issue by bgervan** [mom1/api-client-pydantic#406]
There is something changed in pydantic or pydantic-core which breaks the package the following way:

`module 'pydantic._internal._typing_extra' has no attribute 'add_module_globals'`

As the upper limit is 3.0.0 and not 2.9.0, the breaking change installed by default.

**Comment by roganartu** [comment]
https://github.com/pydantic/pydantic/commit/8dc0ce3c626d49d94ce688ffc450abf2b491aff3 renamed `add_module_globals` to `get_module_ns_of` (and changed the args too).

**Comment by mom1** [comment]
> [pydantic/pydantic@8dc0ce3](https://github.com/pydantic/pydantic/commit/8dc0ce3c626d49d94ce688ffc450abf2b491aff3) renamed `add_module_globals` to `get_module_ns_of` (and changed the args too).

Thank you so much. I'll try to release a fix next week
